[project]
name = "donor-api"
version = "1.0.0"
description = "A simple API for accessing donors from luckperms groups"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "mariadb>=1.1.11",
    "requests>=2.32.3",
]
